version: '3.7'
volumes:
    www:
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${NFS_MOUNT_WWW}"
